/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package TASK2;

//classes
import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author Mveledzo Mbubana
 */
public class NumberGuess {
//Main method

    public static void main(String[] args) {

        //Variables
        double UserInput = 0;
        int RandomNum;
        final int rounds = 3;
        Boolean IsRunning = true;
        int TotalScore=0;
                int roundScore = 0;
        

        //Objects
        Random RandomGen = new Random();
        Scanner objInput = new Scanner(System.in);

        while (IsRunning) {
            for (int i = 0; i < rounds; i++) {
                int rou = i + 1;
                int attempt = 0;
                System.out.println("The computer picked a number between 1 and 100. Try to guess it!");
                System.out.println("ROUND: " + rou);

                RandomNum = RandomGen.nextInt(100) + 1;

                while (UserInput != RandomNum && attempt < 5) {

                    System.out.println("Attempt:" + (attempt + 1));
                    System.out.print("Guess a number between 1-100: ");
                    UserInput = objInput.nextInt();

                    if (UserInput < 1 || UserInput > 100) {
                        System.out.println("Invalid Input");
                    } else {
                        if (UserInput == RandomNum) {
                            System.out.println("Congratulations\nYou Guessed the correct number generated by computer");
                            System.out.println("Generated Number:" + RandomNum);
                            System.out.println("--------------------------------------------------");
                              switch (attempt) {
                                case 0:
                                    roundScore += 5; // 1st attempt
                                    break;
                                case 1:
                                    roundScore += 4; // 2nd attempt
                                    break;
                                case 2:
                                    roundScore += 3; // 3rd attempt
                                    break;
                                case 3:
                                    roundScore += 2; // 4th attempt
                                    break;
                                case 4:
                                    roundScore += 1; // 5th attempt
                                    break;
                                default:
                                    break;
                            
                            }

                        } else if (UserInput > RandomNum) {
                            System.out.println("Ooops..Guessed HIGH number!!!");

                        } else {
                            System.out.println("Oooops..Guessed LOW number");

                        }

                        attempt += 1;

                        if (attempt >= 5 && UserInput != RandomNum) {
                            System.out.println("Round:" + rou + " reached Max attempts(" + (attempt) + ") Try next Round");
                            System.out.println("Generated Number:" + RandomNum + "\n");

                        }

                    }

                }
                


            }
            TotalScore+=roundScore;
            System.out.println("Game Over! Your total score is: " + TotalScore +"of 15" );
            System.out.println("--------------------------------------------------");

        }

    }

}
